name: C++ Integration Tests
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install and run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true

      - id: cmake_configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -Bbuild_test
      - id: cmake_build
        run: cmake --build build_test --target IntegrationTests
      - id: ctest
        run: ctest --test-dir build_test
