name: C++ Integration Tests
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: "3.28.4"
          ninja: true
          vcpkg: true
          ccache: true
          clangtidy: true

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11
        runVcpkgInstall: true

      - id: cmake_configure
        run: cmake -D CMAKE_BUILD_TYPE=Debug -B build_test
      - id: cmake_build
        run: cmake --build build_test --target IntegrationTests
      - id: ctest
        run: ctest --test-dir build_test
