name: C++ Integration Tests
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: cmake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -B../build_test -S. --target IntegrationTests
      - id: ctest
        run: ctest --test-dir build
