name: Finished work
on:
  pull_request:
  push:
    branches: main
jobs:
  build-and-test:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - id: permissions
        run: chmod +x "${GITHUB_WORKSPACE}/.github/workflows/scripts/to-do_check.sh"
      - id: check
        run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/to-do_check.sh
